version: "3.7"

services:

  service-name:
    container_name: app-name
    image: ${DOCKER_REPOSITORY}/${APP_NAME}:${IMAGE_VERSION}    
    restart: always    
    labels:
      - "traefik.http.routers.appname.rule=Host(`${TRAEFIK_HOST_01}`)"
      - "traefik.enable=true"
    env_file: .env
    volumes:
      #- ./app:/app
      - /etc/localtime:/etc/localtime:ro

networks:
  default:
    external:
      name: ${DOCKER_NETWORK}

      
      
