version: "3.7"

services:

  ofelia:
    restart: always
    image: mcuadros/ofelia:latest
    volumes:
      - ./config.ini:/etc/ofelia/config.ini
      - /var/run/docker.sock:/var/run/docker.sock
      # - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

networks:
  default:
    external:
      name: docker_default

      
      
